name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build ausführen
        run: |
          pyinstaller --onefile --windowed --icon=minilink/assets/icon.ico --name=minilink.exe main.py

      - name: Artefakt hochladen
        uses: actions/upload-artifact@v3
        with:
          name: minilink-windows
          path: dist/minilink.exe  # Datei mit .exe-Erweiterung

      - name: Release erstellen
        uses: softprops/action-gh-release@v1
        with:
          files: dist/minilink.exe
